\slot{16:00-16:10} \talk{Robert Ferdman}{Using pulsars in a galactic-scale gravitational-wave detector}

\slot{16:15-16:40} \talk{7 short talks}{3 min each}

\begin{itemize}
\setlength\itemsep{0pt}
\item \talk{Jonathan Thornburg}{Gravity waves from extreme mass ratio inspiral systems}
\item \talk{Walter Del Pozzo}{Testing general relativity with gravitational waves observations}
\item \talk{Emmanuel Fonseca}{A comprehensive study of relativistic gravity using PSR B1534+12}
\item \talk{Jannis R.\ Bielefeld}{ An SU(2) Yang-Mills model of color radiation}
\item \talk{Alexis Helou}{From black holes to cosmology, and back}
\item \talk{Shinsuke Asaba}{Effect of supersonic relative motion on spherical collapse}
\item \talk{Matt Beach}{Self-force on a charge outside a five-dimensional black hole}
\end{itemize}

\slot{16:45-16:55} \talk{Jim Franson}{Supernova 1987a and the equivalence principle}

\slot{17:00-17:25} \talk{7 short talks}{3 min each}

\begin{itemize}
\setlength\itemsep{0pt}
\item \talk{Chryssomalis Chryssomalakos}{Operational geometry with extended probes}
\item \talk{Jeffrey Hyde}{Gravitational waves from preheating of a Higgs-like scalar}
\item \talk{Kei Yamada}{Relativistic Sagnac effects by Chern-Simons gravity}
\item \talk{Alexandra Terrana}{Bigravity theories and gravitational waves}
\item \talk{Ryotaro Kase}{The effective field theory of modified gravity}
\item \talk{Orest Hrycyna}{Dynamics and observational constraints on Brans-Dicke cosmological model}
\item \talk{William Terrano}{Looking for torsion in general relativity, or the role of spin in gravity}
\end{itemize}

\slot{17:25-17:35} \talk{Manu Paranjape}{How to measure the speed of gravity}

\slot{17:40-18:00} \talk{6 short talks}{3 min each}

\begin{itemize}
\setlength\itemsep{0pt}
\item \talk{Amol Upadhye}{Large-scale structure as a test of dark energy and modified gravity}
\item \talk{Alejo Stark}{A novel test of gravity in galaxy cluster scales}
\item \talk{Jacob Moldenhauer}{Interactive testing of cosmological models using the latest data sets in the CosmoEJS package}
\item \talk{Shohei Saga}{More accurate analysis of secondary gravitational waves in LambdaCDM cosmology}
\item \talk{Isoyama Soichiro}{Effective hamilton dynamics of the self-forced motion in Kerr spacetime}
\item \talk{David W.\ Tian}{Thermodynamics-gravity correspondence of the Universe in general relativity and modified gravity}
\end{itemize}
